[workspace]
resolver = "2"
members = [
    "crates/rustbazel",
    "crates/calculator"
]

[workspace.package]
authors = ["Michael Gardner <mjgardner@abitofhelp.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.74"